### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by ultrasplet** [symfony-si/magento2-sl-si#3]
As we all know you did very hard job, therefore please inform us with your PayPal account so we can donate to you.

Thank you very much for this translation!

br, mitja

**Comment by petk** [comment]
Hello @ultrasplet 

Thank you so much for this kind offer. This project is open sourced, no worries. Donate where people need help. Project maintenance is, for now, possible without donations.

In case there are any bugs or typos, just report via tickets. Thanks. :)
